# Generated by Django 3.2.7 on 2022-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('acreage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acreage')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link_Image')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Price')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
    ]
